POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
  "content":"task 2",
  "deadline": "2024-01-10",
  "owner": {
    "name": "Bob",
    "email": "bobby777@gmail.com",
    "rating": 3
  }
}